// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global.proto

package global;

public final class Global {
  private Global() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GlobalHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GlobalHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 cluster_id = 1;</code>
     */
    boolean hasClusterId();
    /**
     * <code>required int32 cluster_id = 1;</code>
     */
    int getClusterId();

    /**
     * <code>required int64 time = 2;</code>
     */
    boolean hasTime();
    /**
     * <code>required int64 time = 2;</code>
     */
    long getTime();

    /**
     * <code>optional int32 destination_id = 8;</code>
     */
    boolean hasDestinationId();
    /**
     * <code>optional int32 destination_id = 8;</code>
     */
    int getDestinationId();

    /**
     * <code>optional int32 max_hops = 10 [default = -1];</code>
     *
     * <pre>
     *todo
     * </pre>
     */
    boolean hasMaxHops();
    /**
     * <code>optional int32 max_hops = 10 [default = -1];</code>
     *
     * <pre>
     *todo
     * </pre>
     */
    int getMaxHops();
  }
  /**
   * Protobuf type {@code GlobalHeader}
   */
  public static final class GlobalHeader extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GlobalHeader)
      GlobalHeaderOrBuilder {
    // Use GlobalHeader.newBuilder() to construct.
    private GlobalHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GlobalHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GlobalHeader defaultInstance;
    public static GlobalHeader getDefaultInstance() {
      return defaultInstance;
    }

    public GlobalHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GlobalHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              clusterId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000004;
              destinationId_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000008;
              maxHops_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return global.Global.internal_static_GlobalHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return global.Global.internal_static_GlobalHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              global.Global.GlobalHeader.class, global.Global.GlobalHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<GlobalHeader> PARSER =
        new com.google.protobuf.AbstractParser<GlobalHeader>() {
      public GlobalHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GlobalHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GlobalHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CLUSTER_ID_FIELD_NUMBER = 1;
    private int clusterId_;
    /**
     * <code>required int32 cluster_id = 1;</code>
     */
    public boolean hasClusterId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cluster_id = 1;</code>
     */
    public int getClusterId() {
      return clusterId_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private long time_;
    /**
     * <code>required int64 time = 2;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 time = 2;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int DESTINATION_ID_FIELD_NUMBER = 8;
    private int destinationId_;
    /**
     * <code>optional int32 destination_id = 8;</code>
     */
    public boolean hasDestinationId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 destination_id = 8;</code>
     */
    public int getDestinationId() {
      return destinationId_;
    }

    public static final int MAX_HOPS_FIELD_NUMBER = 10;
    private int maxHops_;
    /**
     * <code>optional int32 max_hops = 10 [default = -1];</code>
     *
     * <pre>
     *todo
     * </pre>
     */
    public boolean hasMaxHops() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 max_hops = 10 [default = -1];</code>
     *
     * <pre>
     *todo
     * </pre>
     */
    public int getMaxHops() {
      return maxHops_;
    }

    private void initFields() {
      clusterId_ = 0;
      time_ = 0L;
      destinationId_ = 0;
      maxHops_ = -1;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasClusterId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, clusterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(8, destinationId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(10, maxHops_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clusterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, destinationId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, maxHops_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static global.Global.GlobalHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static global.Global.GlobalHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static global.Global.GlobalHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static global.Global.GlobalHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static global.Global.GlobalHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static global.Global.GlobalHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static global.Global.GlobalHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static global.Global.GlobalHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static global.Global.GlobalHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static global.Global.GlobalHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(global.Global.GlobalHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GlobalHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GlobalHeader)
        global.Global.GlobalHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return global.Global.internal_static_GlobalHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return global.Global.internal_static_GlobalHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                global.Global.GlobalHeader.class, global.Global.GlobalHeader.Builder.class);
      }

      // Construct using global.Global.GlobalHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clusterId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        destinationId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        maxHops_ = -1;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return global.Global.internal_static_GlobalHeader_descriptor;
      }

      public global.Global.GlobalHeader getDefaultInstanceForType() {
        return global.Global.GlobalHeader.getDefaultInstance();
      }

      public global.Global.GlobalHeader build() {
        global.Global.GlobalHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public global.Global.GlobalHeader buildPartial() {
        global.Global.GlobalHeader result = new global.Global.GlobalHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clusterId_ = clusterId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.destinationId_ = destinationId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.maxHops_ = maxHops_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof global.Global.GlobalHeader) {
          return mergeFrom((global.Global.GlobalHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(global.Global.GlobalHeader other) {
        if (other == global.Global.GlobalHeader.getDefaultInstance()) return this;
        if (other.hasClusterId()) {
          setClusterId(other.getClusterId());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasDestinationId()) {
          setDestinationId(other.getDestinationId());
        }
        if (other.hasMaxHops()) {
          setMaxHops(other.getMaxHops());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClusterId()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        global.Global.GlobalHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (global.Global.GlobalHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int clusterId_ ;
      /**
       * <code>required int32 cluster_id = 1;</code>
       */
      public boolean hasClusterId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cluster_id = 1;</code>
       */
      public int getClusterId() {
        return clusterId_;
      }
      /**
       * <code>required int32 cluster_id = 1;</code>
       */
      public Builder setClusterId(int value) {
        bitField0_ |= 0x00000001;
        clusterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cluster_id = 1;</code>
       */
      public Builder clearClusterId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clusterId_ = 0;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>required int64 time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 time = 2;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required int64 time = 2;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 time = 2;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0L;
        onChanged();
        return this;
      }

      private int destinationId_ ;
      /**
       * <code>optional int32 destination_id = 8;</code>
       */
      public boolean hasDestinationId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 destination_id = 8;</code>
       */
      public int getDestinationId() {
        return destinationId_;
      }
      /**
       * <code>optional int32 destination_id = 8;</code>
       */
      public Builder setDestinationId(int value) {
        bitField0_ |= 0x00000004;
        destinationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 destination_id = 8;</code>
       */
      public Builder clearDestinationId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        destinationId_ = 0;
        onChanged();
        return this;
      }

      private int maxHops_ = -1;
      /**
       * <code>optional int32 max_hops = 10 [default = -1];</code>
       *
       * <pre>
       *todo
       * </pre>
       */
      public boolean hasMaxHops() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 max_hops = 10 [default = -1];</code>
       *
       * <pre>
       *todo
       * </pre>
       */
      public int getMaxHops() {
        return maxHops_;
      }
      /**
       * <code>optional int32 max_hops = 10 [default = -1];</code>
       *
       * <pre>
       *todo
       * </pre>
       */
      public Builder setMaxHops(int value) {
        bitField0_ |= 0x00000008;
        maxHops_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 max_hops = 10 [default = -1];</code>
       *
       * <pre>
       *todo
       * </pre>
       */
      public Builder clearMaxHops() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maxHops_ = -1;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GlobalHeader)
    }

    static {
      defaultInstance = new GlobalHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GlobalHeader)
  }

  public interface GlobalMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GlobalMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .GlobalHeader globalHeader = 1;</code>
     */
    boolean hasGlobalHeader();
    /**
     * <code>required .GlobalHeader globalHeader = 1;</code>
     */
    global.Global.GlobalHeader getGlobalHeader();
    /**
     * <code>required .GlobalHeader globalHeader = 1;</code>
     */
    global.Global.GlobalHeaderOrBuilder getGlobalHeaderOrBuilder();

    /**
     * <code>optional bool ping = 2;</code>
     */
    boolean hasPing();
    /**
     * <code>optional bool ping = 2;</code>
     */
    boolean getPing();

    /**
     * <code>optional string message = 3;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional .Failure failure = 4;</code>
     */
    boolean hasFailure();
    /**
     * <code>optional .Failure failure = 4;</code>
     */
    pipe.common.Common.Failure getFailure();
    /**
     * <code>optional .Failure failure = 4;</code>
     */
    pipe.common.Common.FailureOrBuilder getFailureOrBuilder();

    /**
     * <code>optional .Request request = 5;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .Request request = 5;</code>
     */
    pipe.common.Common.Request getRequest();
    /**
     * <code>optional .Request request = 5;</code>
     */
    pipe.common.Common.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .Response response = 6;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .Response response = 6;</code>
     */
    pipe.common.Common.Response getResponse();
    /**
     * <code>optional .Response response = 6;</code>
     */
    pipe.common.Common.ResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code GlobalMessage}
   */
  public static final class GlobalMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GlobalMessage)
      GlobalMessageOrBuilder {
    // Use GlobalMessage.newBuilder() to construct.
    private GlobalMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GlobalMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GlobalMessage defaultInstance;
    public static GlobalMessage getDefaultInstance() {
      return defaultInstance;
    }

    public GlobalMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GlobalMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              global.Global.GlobalHeader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = globalHeader_.toBuilder();
              }
              globalHeader_ = input.readMessage(global.Global.GlobalHeader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(globalHeader_);
                globalHeader_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              payloadCase_ = 2;
              payload_ = input.readBool();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              payloadCase_ = 3;
              payload_ = bs;
              break;
            }
            case 34: {
              pipe.common.Common.Failure.Builder subBuilder = null;
              if (payloadCase_ == 4) {
                subBuilder = ((pipe.common.Common.Failure) payload_).toBuilder();
              }
              payload_ = input.readMessage(pipe.common.Common.Failure.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.common.Common.Failure) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 4;
              break;
            }
            case 42: {
              pipe.common.Common.Request.Builder subBuilder = null;
              if (payloadCase_ == 5) {
                subBuilder = ((pipe.common.Common.Request) payload_).toBuilder();
              }
              payload_ = input.readMessage(pipe.common.Common.Request.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.common.Common.Request) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 5;
              break;
            }
            case 50: {
              pipe.common.Common.Response.Builder subBuilder = null;
              if (payloadCase_ == 6) {
                subBuilder = ((pipe.common.Common.Response) payload_).toBuilder();
              }
              payload_ = input.readMessage(pipe.common.Common.Response.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.common.Common.Response) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 6;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return global.Global.internal_static_GlobalMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return global.Global.internal_static_GlobalMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              global.Global.GlobalMessage.class, global.Global.GlobalMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<GlobalMessage> PARSER =
        new com.google.protobuf.AbstractParser<GlobalMessage>() {
      public GlobalMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GlobalMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GlobalMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      PING(2),
      MESSAGE(3),
      FAILURE(4),
      REQUEST(5),
      RESPONSE(6),
      PAYLOAD_NOT_SET(0);
      private int value = 0;
      private PayloadCase(int value) {
        this.value = value;
      }
      public static PayloadCase valueOf(int value) {
        switch (value) {
          case 2: return PING;
          case 3: return MESSAGE;
          case 4: return FAILURE;
          case 5: return REQUEST;
          case 6: return RESPONSE;
          case 0: return PAYLOAD_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.valueOf(
          payloadCase_);
    }

    public static final int GLOBALHEADER_FIELD_NUMBER = 1;
    private global.Global.GlobalHeader globalHeader_;
    /**
     * <code>required .GlobalHeader globalHeader = 1;</code>
     */
    public boolean hasGlobalHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .GlobalHeader globalHeader = 1;</code>
     */
    public global.Global.GlobalHeader getGlobalHeader() {
      return globalHeader_;
    }
    /**
     * <code>required .GlobalHeader globalHeader = 1;</code>
     */
    public global.Global.GlobalHeaderOrBuilder getGlobalHeaderOrBuilder() {
      return globalHeader_;
    }

    public static final int PING_FIELD_NUMBER = 2;
    /**
     * <code>optional bool ping = 2;</code>
     */
    public boolean hasPing() {
      return payloadCase_ == 2;
    }
    /**
     * <code>optional bool ping = 2;</code>
     */
    public boolean getPing() {
      if (payloadCase_ == 2) {
        return (java.lang.Boolean) payload_;
      }
      return false;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    /**
     * <code>optional string message = 3;</code>
     */
    public boolean hasMessage() {
      return payloadCase_ == 3;
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = "";
      if (payloadCase_ == 3) {
        ref = payload_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8() && (payloadCase_ == 3)) {
          payload_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = "";
      if (payloadCase_ == 3) {
        ref = payload_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (payloadCase_ == 3) {
          payload_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FAILURE_FIELD_NUMBER = 4;
    /**
     * <code>optional .Failure failure = 4;</code>
     */
    public boolean hasFailure() {
      return payloadCase_ == 4;
    }
    /**
     * <code>optional .Failure failure = 4;</code>
     */
    public pipe.common.Common.Failure getFailure() {
      if (payloadCase_ == 4) {
         return (pipe.common.Common.Failure) payload_;
      }
      return pipe.common.Common.Failure.getDefaultInstance();
    }
    /**
     * <code>optional .Failure failure = 4;</code>
     */
    public pipe.common.Common.FailureOrBuilder getFailureOrBuilder() {
      if (payloadCase_ == 4) {
         return (pipe.common.Common.Failure) payload_;
      }
      return pipe.common.Common.Failure.getDefaultInstance();
    }

    public static final int REQUEST_FIELD_NUMBER = 5;
    /**
     * <code>optional .Request request = 5;</code>
     */
    public boolean hasRequest() {
      return payloadCase_ == 5;
    }
    /**
     * <code>optional .Request request = 5;</code>
     */
    public pipe.common.Common.Request getRequest() {
      if (payloadCase_ == 5) {
         return (pipe.common.Common.Request) payload_;
      }
      return pipe.common.Common.Request.getDefaultInstance();
    }
    /**
     * <code>optional .Request request = 5;</code>
     */
    public pipe.common.Common.RequestOrBuilder getRequestOrBuilder() {
      if (payloadCase_ == 5) {
         return (pipe.common.Common.Request) payload_;
      }
      return pipe.common.Common.Request.getDefaultInstance();
    }

    public static final int RESPONSE_FIELD_NUMBER = 6;
    /**
     * <code>optional .Response response = 6;</code>
     */
    public boolean hasResponse() {
      return payloadCase_ == 6;
    }
    /**
     * <code>optional .Response response = 6;</code>
     */
    public pipe.common.Common.Response getResponse() {
      if (payloadCase_ == 6) {
         return (pipe.common.Common.Response) payload_;
      }
      return pipe.common.Common.Response.getDefaultInstance();
    }
    /**
     * <code>optional .Response response = 6;</code>
     */
    public pipe.common.Common.ResponseOrBuilder getResponseOrBuilder() {
      if (payloadCase_ == 6) {
         return (pipe.common.Common.Response) payload_;
      }
      return pipe.common.Common.Response.getDefaultInstance();
    }

    private void initFields() {
      globalHeader_ = global.Global.GlobalHeader.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasGlobalHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getGlobalHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasFailure()) {
        if (!getFailure().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResponse()) {
        if (!getResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, globalHeader_);
      }
      if (payloadCase_ == 2) {
        output.writeBool(
            2, (boolean)((java.lang.Boolean) payload_));
      }
      if (payloadCase_ == 3) {
        output.writeBytes(3, getMessageBytes());
      }
      if (payloadCase_ == 4) {
        output.writeMessage(4, (pipe.common.Common.Failure) payload_);
      }
      if (payloadCase_ == 5) {
        output.writeMessage(5, (pipe.common.Common.Request) payload_);
      }
      if (payloadCase_ == 6) {
        output.writeMessage(6, (pipe.common.Common.Response) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, globalHeader_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              2, (boolean)((java.lang.Boolean) payload_));
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMessageBytes());
      }
      if (payloadCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (pipe.common.Common.Failure) payload_);
      }
      if (payloadCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (pipe.common.Common.Request) payload_);
      }
      if (payloadCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (pipe.common.Common.Response) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static global.Global.GlobalMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static global.Global.GlobalMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static global.Global.GlobalMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static global.Global.GlobalMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static global.Global.GlobalMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static global.Global.GlobalMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static global.Global.GlobalMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static global.Global.GlobalMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static global.Global.GlobalMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static global.Global.GlobalMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(global.Global.GlobalMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GlobalMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GlobalMessage)
        global.Global.GlobalMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return global.Global.internal_static_GlobalMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return global.Global.internal_static_GlobalMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                global.Global.GlobalMessage.class, global.Global.GlobalMessage.Builder.class);
      }

      // Construct using global.Global.GlobalMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGlobalHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (globalHeaderBuilder_ == null) {
          globalHeader_ = global.Global.GlobalHeader.getDefaultInstance();
        } else {
          globalHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return global.Global.internal_static_GlobalMessage_descriptor;
      }

      public global.Global.GlobalMessage getDefaultInstanceForType() {
        return global.Global.GlobalMessage.getDefaultInstance();
      }

      public global.Global.GlobalMessage build() {
        global.Global.GlobalMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public global.Global.GlobalMessage buildPartial() {
        global.Global.GlobalMessage result = new global.Global.GlobalMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (globalHeaderBuilder_ == null) {
          result.globalHeader_ = globalHeader_;
        } else {
          result.globalHeader_ = globalHeaderBuilder_.build();
        }
        if (payloadCase_ == 2) {
          result.payload_ = payload_;
        }
        if (payloadCase_ == 3) {
          result.payload_ = payload_;
        }
        if (payloadCase_ == 4) {
          if (failureBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = failureBuilder_.build();
          }
        }
        if (payloadCase_ == 5) {
          if (requestBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = requestBuilder_.build();
          }
        }
        if (payloadCase_ == 6) {
          if (responseBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = responseBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof global.Global.GlobalMessage) {
          return mergeFrom((global.Global.GlobalMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(global.Global.GlobalMessage other) {
        if (other == global.Global.GlobalMessage.getDefaultInstance()) return this;
        if (other.hasGlobalHeader()) {
          mergeGlobalHeader(other.getGlobalHeader());
        }
        switch (other.getPayloadCase()) {
          case PING: {
            setPing(other.getPing());
            break;
          }
          case MESSAGE: {
            payloadCase_ = 3;
            payload_ = other.payload_;
            onChanged();
            break;
          }
          case FAILURE: {
            mergeFailure(other.getFailure());
            break;
          }
          case REQUEST: {
            mergeRequest(other.getRequest());
            break;
          }
          case RESPONSE: {
            mergeResponse(other.getResponse());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGlobalHeader()) {
          
          return false;
        }
        if (!getGlobalHeader().isInitialized()) {
          
          return false;
        }
        if (hasFailure()) {
          if (!getFailure().isInitialized()) {
            
            return false;
          }
        }
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasResponse()) {
          if (!getResponse().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        global.Global.GlobalMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (global.Global.GlobalMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.valueOf(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private global.Global.GlobalHeader globalHeader_ = global.Global.GlobalHeader.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          global.Global.GlobalHeader, global.Global.GlobalHeader.Builder, global.Global.GlobalHeaderOrBuilder> globalHeaderBuilder_;
      /**
       * <code>required .GlobalHeader globalHeader = 1;</code>
       */
      public boolean hasGlobalHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .GlobalHeader globalHeader = 1;</code>
       */
      public global.Global.GlobalHeader getGlobalHeader() {
        if (globalHeaderBuilder_ == null) {
          return globalHeader_;
        } else {
          return globalHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>required .GlobalHeader globalHeader = 1;</code>
       */
      public Builder setGlobalHeader(global.Global.GlobalHeader value) {
        if (globalHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          globalHeader_ = value;
          onChanged();
        } else {
          globalHeaderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .GlobalHeader globalHeader = 1;</code>
       */
      public Builder setGlobalHeader(
          global.Global.GlobalHeader.Builder builderForValue) {
        if (globalHeaderBuilder_ == null) {
          globalHeader_ = builderForValue.build();
          onChanged();
        } else {
          globalHeaderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .GlobalHeader globalHeader = 1;</code>
       */
      public Builder mergeGlobalHeader(global.Global.GlobalHeader value) {
        if (globalHeaderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              globalHeader_ != global.Global.GlobalHeader.getDefaultInstance()) {
            globalHeader_ =
              global.Global.GlobalHeader.newBuilder(globalHeader_).mergeFrom(value).buildPartial();
          } else {
            globalHeader_ = value;
          }
          onChanged();
        } else {
          globalHeaderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .GlobalHeader globalHeader = 1;</code>
       */
      public Builder clearGlobalHeader() {
        if (globalHeaderBuilder_ == null) {
          globalHeader_ = global.Global.GlobalHeader.getDefaultInstance();
          onChanged();
        } else {
          globalHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .GlobalHeader globalHeader = 1;</code>
       */
      public global.Global.GlobalHeader.Builder getGlobalHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getGlobalHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .GlobalHeader globalHeader = 1;</code>
       */
      public global.Global.GlobalHeaderOrBuilder getGlobalHeaderOrBuilder() {
        if (globalHeaderBuilder_ != null) {
          return globalHeaderBuilder_.getMessageOrBuilder();
        } else {
          return globalHeader_;
        }
      }
      /**
       * <code>required .GlobalHeader globalHeader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          global.Global.GlobalHeader, global.Global.GlobalHeader.Builder, global.Global.GlobalHeaderOrBuilder> 
          getGlobalHeaderFieldBuilder() {
        if (globalHeaderBuilder_ == null) {
          globalHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              global.Global.GlobalHeader, global.Global.GlobalHeader.Builder, global.Global.GlobalHeaderOrBuilder>(
                  getGlobalHeader(),
                  getParentForChildren(),
                  isClean());
          globalHeader_ = null;
        }
        return globalHeaderBuilder_;
      }

      /**
       * <code>optional bool ping = 2;</code>
       */
      public boolean hasPing() {
        return payloadCase_ == 2;
      }
      /**
       * <code>optional bool ping = 2;</code>
       */
      public boolean getPing() {
        if (payloadCase_ == 2) {
          return (java.lang.Boolean) payload_;
        }
        return false;
      }
      /**
       * <code>optional bool ping = 2;</code>
       */
      public Builder setPing(boolean value) {
        payloadCase_ = 2;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool ping = 2;</code>
       */
      public Builder clearPing() {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional string message = 3;</code>
       */
      public boolean hasMessage() {
        return payloadCase_ == 3;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = "";
        if (payloadCase_ == 3) {
          ref = payload_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (payloadCase_ == 3) {
            if (bs.isValidUtf8()) {
              payload_ = s;
            }
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = "";
        if (payloadCase_ == 3) {
          ref = payload_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (payloadCase_ == 3) {
            payload_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  payloadCase_ = 3;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder clearMessage() {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  payloadCase_ = 3;
        payload_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          pipe.common.Common.Failure, pipe.common.Common.Failure.Builder, pipe.common.Common.FailureOrBuilder> failureBuilder_;
      /**
       * <code>optional .Failure failure = 4;</code>
       */
      public boolean hasFailure() {
        return payloadCase_ == 4;
      }
      /**
       * <code>optional .Failure failure = 4;</code>
       */
      public pipe.common.Common.Failure getFailure() {
        if (failureBuilder_ == null) {
          if (payloadCase_ == 4) {
            return (pipe.common.Common.Failure) payload_;
          }
          return pipe.common.Common.Failure.getDefaultInstance();
        } else {
          if (payloadCase_ == 4) {
            return failureBuilder_.getMessage();
          }
          return pipe.common.Common.Failure.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Failure failure = 4;</code>
       */
      public Builder setFailure(pipe.common.Common.Failure value) {
        if (failureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          failureBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .Failure failure = 4;</code>
       */
      public Builder setFailure(
          pipe.common.Common.Failure.Builder builderForValue) {
        if (failureBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          failureBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .Failure failure = 4;</code>
       */
      public Builder mergeFailure(pipe.common.Common.Failure value) {
        if (failureBuilder_ == null) {
          if (payloadCase_ == 4 &&
              payload_ != pipe.common.Common.Failure.getDefaultInstance()) {
            payload_ = pipe.common.Common.Failure.newBuilder((pipe.common.Common.Failure) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 4) {
            failureBuilder_.mergeFrom(value);
          }
          failureBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .Failure failure = 4;</code>
       */
      public Builder clearFailure() {
        if (failureBuilder_ == null) {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
          }
          failureBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Failure failure = 4;</code>
       */
      public pipe.common.Common.Failure.Builder getFailureBuilder() {
        return getFailureFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Failure failure = 4;</code>
       */
      public pipe.common.Common.FailureOrBuilder getFailureOrBuilder() {
        if ((payloadCase_ == 4) && (failureBuilder_ != null)) {
          return failureBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 4) {
            return (pipe.common.Common.Failure) payload_;
          }
          return pipe.common.Common.Failure.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Failure failure = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          pipe.common.Common.Failure, pipe.common.Common.Failure.Builder, pipe.common.Common.FailureOrBuilder> 
          getFailureFieldBuilder() {
        if (failureBuilder_ == null) {
          if (!(payloadCase_ == 4)) {
            payload_ = pipe.common.Common.Failure.getDefaultInstance();
          }
          failureBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pipe.common.Common.Failure, pipe.common.Common.Failure.Builder, pipe.common.Common.FailureOrBuilder>(
                  (pipe.common.Common.Failure) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 4;
        return failureBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          pipe.common.Common.Request, pipe.common.Common.Request.Builder, pipe.common.Common.RequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .Request request = 5;</code>
       */
      public boolean hasRequest() {
        return payloadCase_ == 5;
      }
      /**
       * <code>optional .Request request = 5;</code>
       */
      public pipe.common.Common.Request getRequest() {
        if (requestBuilder_ == null) {
          if (payloadCase_ == 5) {
            return (pipe.common.Common.Request) payload_;
          }
          return pipe.common.Common.Request.getDefaultInstance();
        } else {
          if (payloadCase_ == 5) {
            return requestBuilder_.getMessage();
          }
          return pipe.common.Common.Request.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Request request = 5;</code>
       */
      public Builder setRequest(pipe.common.Common.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .Request request = 5;</code>
       */
      public Builder setRequest(
          pipe.common.Common.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .Request request = 5;</code>
       */
      public Builder mergeRequest(pipe.common.Common.Request value) {
        if (requestBuilder_ == null) {
          if (payloadCase_ == 5 &&
              payload_ != pipe.common.Common.Request.getDefaultInstance()) {
            payload_ = pipe.common.Common.Request.newBuilder((pipe.common.Common.Request) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 5) {
            requestBuilder_.mergeFrom(value);
          }
          requestBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .Request request = 5;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
          }
          requestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Request request = 5;</code>
       */
      public pipe.common.Common.Request.Builder getRequestBuilder() {
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Request request = 5;</code>
       */
      public pipe.common.Common.RequestOrBuilder getRequestOrBuilder() {
        if ((payloadCase_ == 5) && (requestBuilder_ != null)) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 5) {
            return (pipe.common.Common.Request) payload_;
          }
          return pipe.common.Common.Request.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Request request = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          pipe.common.Common.Request, pipe.common.Common.Request.Builder, pipe.common.Common.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          if (!(payloadCase_ == 5)) {
            payload_ = pipe.common.Common.Request.getDefaultInstance();
          }
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pipe.common.Common.Request, pipe.common.Common.Request.Builder, pipe.common.Common.RequestOrBuilder>(
                  (pipe.common.Common.Request) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 5;
        return requestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          pipe.common.Common.Response, pipe.common.Common.Response.Builder, pipe.common.Common.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .Response response = 6;</code>
       */
      public boolean hasResponse() {
        return payloadCase_ == 6;
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public pipe.common.Common.Response getResponse() {
        if (responseBuilder_ == null) {
          if (payloadCase_ == 6) {
            return (pipe.common.Common.Response) payload_;
          }
          return pipe.common.Common.Response.getDefaultInstance();
        } else {
          if (payloadCase_ == 6) {
            return responseBuilder_.getMessage();
          }
          return pipe.common.Common.Response.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public Builder setResponse(pipe.common.Common.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public Builder setResponse(
          pipe.common.Common.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public Builder mergeResponse(pipe.common.Common.Response value) {
        if (responseBuilder_ == null) {
          if (payloadCase_ == 6 &&
              payload_ != pipe.common.Common.Response.getDefaultInstance()) {
            payload_ = pipe.common.Common.Response.newBuilder((pipe.common.Common.Response) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 6) {
            responseBuilder_.mergeFrom(value);
          }
          responseBuilder_.setMessage(value);
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          if (payloadCase_ == 6) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 6) {
            payloadCase_ = 0;
            payload_ = null;
          }
          responseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public pipe.common.Common.Response.Builder getResponseBuilder() {
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      public pipe.common.Common.ResponseOrBuilder getResponseOrBuilder() {
        if ((payloadCase_ == 6) && (responseBuilder_ != null)) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 6) {
            return (pipe.common.Common.Response) payload_;
          }
          return pipe.common.Common.Response.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Response response = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          pipe.common.Common.Response, pipe.common.Common.Response.Builder, pipe.common.Common.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          if (!(payloadCase_ == 6)) {
            payload_ = pipe.common.Common.Response.getDefaultInstance();
          }
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pipe.common.Common.Response, pipe.common.Common.Response.Builder, pipe.common.Common.ResponseOrBuilder>(
                  (pipe.common.Common.Response) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 6;
        return responseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:GlobalMessage)
    }

    static {
      defaultInstance = new GlobalMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GlobalMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GlobalHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GlobalMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014global.proto\032\014common.proto\"^\n\014GlobalHe" +
      "ader\022\022\n\ncluster_id\030\001 \002(\005\022\014\n\004time\030\002 \002(\003\022\026" +
      "\n\016destination_id\030\010 \001(\005\022\024\n\010max_hops\030\n \001(\005" +
      ":\002-1\"\273\001\n\rGlobalMessage\022#\n\014globalHeader\030\001" +
      " \002(\0132\r.GlobalHeader\022\016\n\004ping\030\002 \001(\010H\000\022\021\n\007m" +
      "essage\030\003 \001(\tH\000\022\033\n\007failure\030\004 \001(\0132\010.Failur" +
      "eH\000\022\033\n\007request\030\005 \001(\0132\010.RequestH\000\022\035\n\010resp" +
      "onse\030\006 \001(\0132\t.ResponseH\000B\t\n\007payloadB\n\n\006gl" +
      "obalH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pipe.common.Common.getDescriptor(),
        }, assigner);
    internal_static_GlobalHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GlobalHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GlobalHeader_descriptor,
        new java.lang.String[] { "ClusterId", "Time", "DestinationId", "MaxHops", });
    internal_static_GlobalMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GlobalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GlobalMessage_descriptor,
        new java.lang.String[] { "GlobalHeader", "Ping", "Message", "Failure", "Request", "Response", "Payload", });
    pipe.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
