# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='clientMessage.proto',
  package='',
  serialized_pb=_b('\n\x13\x63lientMessage.proto\x1a\x0c\x63ommon.proto\"y\n\x0eRequestMessage\x12\x1d\n\toperation\x18\x05 \x01(\x0e\x32\n.Operation\x12\x0b\n\x03key\x18\x06 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\x0c\x12\x0e\n\x06seq_no\x18\x08 \x01(\x05\x12\x1d\n\tchunkInfo\x18\x10 \x01(\x0b\x32\n.ChunkInfo\"A\n\tChunkInfo\x12\x14\n\x0cno_of_chunks\x18\x0f \x02(\x05\x12\x10\n\x08seq_size\x18\x02 \x01(\x03\x12\x0c\n\x04time\x18\x03 \x01(\x03\"\xcd\x01\n\x0fResponseMessage\x12\x1d\n\toperation\x18\t \x01(\x0e\x32\n.Operation\x12\x0f\n\x07success\x18\n \x01(\x08\x12\x0b\n\x03key\x18\x0b \x01(\t\x12\x10\n\x08\x63hunk_no\x18\x0c \x01(\x05\x12\x12\n\nstatus_msg\x18\r \x01(\t\x12\x1b\n\x07\x66\x61ilure\x18\x14 \x01(\x0b\x32\x08.FailureH\x00\x12\x0e\n\x04\x64\x61ta\x18\x13 \x01(\x0cH\x00\x12\x1f\n\tchunkInfo\x18\x12 \x01(\x0b\x32\n.ChunkInfoH\x00\x42\t\n\x07payload*>\n\tOperation\x12\x07\n\x03GET\x10\x01\x12\x08\n\x04POST\x10\x02\x12\x07\n\x03PUT\x10\x03\x12\n\n\x06\x44\x45LETE\x10\x04\x12\t\n\x05STEAL\x10\x05\x42\r\n\x0b\x63om.message')
  ,
  dependencies=[common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POST', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUT', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STEAL', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=435,
  serialized_end=497,
)
_sym_db.RegisterEnumDescriptor(_OPERATION)

Operation = enum_type_wrapper.EnumTypeWrapper(_OPERATION)
GET = 1
POST = 2
PUT = 3
DELETE = 4
STEAL = 5



_REQUESTMESSAGE = _descriptor.Descriptor(
  name='RequestMessage',
  full_name='RequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='RequestMessage.operation', index=0,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='RequestMessage.key', index=1,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='RequestMessage.data', index=2,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq_no', full_name='RequestMessage.seq_no', index=3,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chunkInfo', full_name='RequestMessage.chunkInfo', index=4,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=158,
)


_CHUNKINFO = _descriptor.Descriptor(
  name='ChunkInfo',
  full_name='ChunkInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='no_of_chunks', full_name='ChunkInfo.no_of_chunks', index=0,
      number=15, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq_size', full_name='ChunkInfo.seq_size', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='ChunkInfo.time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=225,
)


_RESPONSEMESSAGE = _descriptor.Descriptor(
  name='ResponseMessage',
  full_name='ResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='ResponseMessage.operation', index=0,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='ResponseMessage.success', index=1,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='ResponseMessage.key', index=2,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chunk_no', full_name='ResponseMessage.chunk_no', index=3,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_msg', full_name='ResponseMessage.status_msg', index=4,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failure', full_name='ResponseMessage.failure', index=5,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ResponseMessage.data', index=6,
      number=19, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chunkInfo', full_name='ResponseMessage.chunkInfo', index=7,
      number=18, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='ResponseMessage.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=228,
  serialized_end=433,
)

_REQUESTMESSAGE.fields_by_name['operation'].enum_type = _OPERATION
_REQUESTMESSAGE.fields_by_name['chunkInfo'].message_type = _CHUNKINFO
_RESPONSEMESSAGE.fields_by_name['operation'].enum_type = _OPERATION
_RESPONSEMESSAGE.fields_by_name['failure'].message_type = common_pb2._FAILURE
_RESPONSEMESSAGE.fields_by_name['chunkInfo'].message_type = _CHUNKINFO
_RESPONSEMESSAGE.oneofs_by_name['payload'].fields.append(
  _RESPONSEMESSAGE.fields_by_name['failure'])
_RESPONSEMESSAGE.fields_by_name['failure'].containing_oneof = _RESPONSEMESSAGE.oneofs_by_name['payload']
_RESPONSEMESSAGE.oneofs_by_name['payload'].fields.append(
  _RESPONSEMESSAGE.fields_by_name['data'])
_RESPONSEMESSAGE.fields_by_name['data'].containing_oneof = _RESPONSEMESSAGE.oneofs_by_name['payload']
_RESPONSEMESSAGE.oneofs_by_name['payload'].fields.append(
  _RESPONSEMESSAGE.fields_by_name['chunkInfo'])
_RESPONSEMESSAGE.fields_by_name['chunkInfo'].containing_oneof = _RESPONSEMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['RequestMessage'] = _REQUESTMESSAGE
DESCRIPTOR.message_types_by_name['ChunkInfo'] = _CHUNKINFO
DESCRIPTOR.message_types_by_name['ResponseMessage'] = _RESPONSEMESSAGE
DESCRIPTOR.enum_types_by_name['Operation'] = _OPERATION

RequestMessage = _reflection.GeneratedProtocolMessageType('RequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTMESSAGE,
  __module__ = 'clientMessage_pb2'
  # @@protoc_insertion_point(class_scope:RequestMessage)
  ))
_sym_db.RegisterMessage(RequestMessage)

ChunkInfo = _reflection.GeneratedProtocolMessageType('ChunkInfo', (_message.Message,), dict(
  DESCRIPTOR = _CHUNKINFO,
  __module__ = 'clientMessage_pb2'
  # @@protoc_insertion_point(class_scope:ChunkInfo)
  ))
_sym_db.RegisterMessage(ChunkInfo)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEMESSAGE,
  __module__ = 'clientMessage_pb2'
  # @@protoc_insertion_point(class_scope:ResponseMessage)
  ))
_sym_db.RegisterMessage(ResponseMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\013com.message'))
# @@protoc_insertion_point(module_scope)
